repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=10240']
      - id: debug-statements
      - id: detect-private-key
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy tests src
        pass_filenames: false
        language: system
        types: [python]
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
      - id: ruff
        name: ruff
        entry: poetry run ruff check --fix
        language: system
        types: [python]