repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=10240']
      - id: debug-statements
      - id: detect-private-key
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy tests src
        pass_filenames: false
        language: system
        files: '^(src|tests)/.*\.py$'
